// Create poll
POST http://localhost:3333/polls
Content-Type: application/json

{
  "title": "What's the best Node.js framework?",
  "options": ["Express", "Fastify", "NestJS", "HapiJS"]
}

###

// Get poll
GET http://localhost:3333/polls/4e09d7ba-e8d2-47bb-9f8c-b34622e74da3

###

// Vote on poll
POST http://localhost:3333/polls/4e09d7ba-e8d2-47bb-9f8c-b34622e74da3/votes
Content-Type: application/json

{
  "pollOptionId": "acb2db24-8946-4c1d-9194-a7d1ad2f4962"
}

###

ws://localhost:3333/polls/4e09d7ba-e8d2-47bb-9f8c-b34622e74da3/results
